### ISSUE TITLE
Rollout UI Gem out of date

### ISSUE THREAD

**Issue by ericboehs** [jrallison/rollout_ui#21]
The Rollout UI gem is over a year out of date. It does not work with rollout 1.2. Can we get an update please? :)

Thanks.

**Comment by bbauer** [comment]
Bump...

**Comment by bbauer** [comment]
The latest gem release of rollout_ui uses the wrong layout by default. This was fixed in September 2012 but never released. The last gem release was March 2012.

**Comment by andrewhao** [comment]
+1

**Comment by jrallison** [comment]
Hey everyone, just pushed a new version.  Sorry about the delay, updated my github notification settings to make sure I hear about these requests :)
